[indicator]
parent = { fg = "#ffffff", bg = "#e1579c" }
current = { fg = "#ffffff", bg = "#e1579c" }
preview = { fg = "#e1579c" }
padding = { open = " ", close = " " }

[filetype]
rules = [{ name = "*/", fg = "#999999" }]
